### ISSUE TITLE
Tried replace pytuya with this, didnt quite work.

### ISSUE THREAD

**Issue by cicci44** [TradeFace/tuya#10]
Simply tried running this
```
cd ~/domoticz/plugins
git clone https://github.com/tixi/Domoticz-Tuya-SmartPlug-Plugin
cd Domoticz-Tuya-SmartPlug-Plugin
# OLD git clone https://github.com/clach04/python-tuya.git
git clone https://github.com/TradeFace/tuya.git
mv /tuya python-tuya
ln -s ~/domoticz/plugins/Domoticz-Tuya-SmartPlug-Plugin/python-tuya pytuya
# restart domoticz:
sudo /etc/init.d/domoticz.sh restart
```
Didnt quite work, some issues i dont 
```
module import failed exception 'modulenotfounderror'
module import failed exception 'name: bitstring'
```
it didnt work. How will this rewritted pytuya be corrected installed with/without clach04s? 

for the moment im going to test the mqtt solution you provided using tuya but im not familiar to mqtt but i guess i need to learn :)

**Comment by TradeFace** [comment]
this lib was not intended as a drop in replacement. The interfaces have been changed / cleaned up. I guess, if there is enough need for it, an interface or middleware could be written to support existing scripts. But I'd rather not put that spaghetti back in.
