### ISSUE TITLE
setup.py is broken

### ISSUE THREAD

**Issue by jkerdreux-imt** [TradeFace/tuya#11]
Could you please fix the setup.py ? 

1) setup.py import tuya, but the directory structure is wrong, so this can't work
2) missing bitstring requirement

2 persons already forked this repo to able to install it.

Please checkout @AlexOwl modifications : 
https://github.com/AlexOwl/tuya

**Comment by TradeFace** [comment]
Oh didn't know it was broken. I don't use it in tuyamqtt. Will take a look at it when I have time.

**Comment by jkerdreux-imt** [comment]
Thanks

**Comment by TradeFace** [comment]
Changed the setup and added the lib to Pypi [https://pypi.org/project/tuyaface/1.0.5/](https://pypi.org/project/tuyaface/1.0.5/)

**Comment by jkerdreux-imt** [comment]
Still not working. 
import tuyaface in setup.py => cause a import error of bitstring. 
You can put version / author in a seperate file.

**Comment by TradeFace** [comment]
Hmm that is strange... I implemented tuyaface lib in tuyamqtt with out a problem. I don't understand what you are saying about separate files... (first python lib I wrote)

**Comment by jkerdreux-imt** [comment]
pip uninstall bitstring & tuyaface.
Then run pip install tuyaface. 

You will see the issue. 

Check how @AlexOwl fixed that. He added a seperated file (const.py) that contains only version / authors..

**Comment by jkerdreux-imt** [comment]
I should have done a pull-request. (my bad)

**Comment by jkerdreux-imt** [comment]
done
