### ISSUE TITLE
Error in status introduced w/ release 1.1.1

### ISSUE THREAD

**Issue by jkerdreux-imt** [TradeFace/tuya#20]
The release 1.1.1 introduced a error for some devices (here LSC lamps)

Look at this  w/ 1.1.0 

```
2020-05-01 16:17:26 i7 tuyaface[2334401] DEBUG Connecting to 192.168.1.65
2020-05-01 16:17:26 i7 tuyaface[2334401] DEBUG sending command: [10] payload: [None]
2020-05-01 16:17:26 i7 tuyaface[2334401] DEBUG Connecting to 192.168.1.65
2020-05-01 16:17:26 i7 tuyaface[2334401] DEBUG sending command: [13] payload: [None]
2020-05-01 16:17:26 i7 tuyaface[2334401] DEBUG reply: {"dps":{"1":false,"2":"colour","3":25},"t":1588342645}

```

The API send command 10, and after no answser switch to 13. 
In 1.1.1 (en 1.1.2) 

```
2020-05-01 16:17:42 i7 tuyaface[2334447] DEBUG Connecting to 192.168.1.65
2020-05-01 16:17:42 i7 tuyaface[2334447] DEBUG sending command: [10] payload: [None]
2020-05-01 16:17:42 i7 tuyaface[2334447] DEBUG reply: b'json obj data unvalid'
*** json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

The new version raise an exception on json obj .. 
I'm not sure why this occur and to busy to search right now.

**Comment by TradeFace** [comment]
Thanks for the report. in v1.1.1 i replaced pycrypto with pycryptodome. As far as I can tell pycryptodome should be a drop in replacement for the functions used. AES crypt / decrypt. I did you install the requirements.txt with v1.1.1?

**Comment by jkerdreux-imt** [comment]
This is not a issue related to missing pycryptodome. (You should fix the setup.py for this requirement too).

**Comment by TradeFace** [comment]
That is strange that was the only change in v1.1.1 (besides a readme update)

yes you are right, I forgot. Will correct the setup.py later today.

**Comment by TradeFace** [comment]
I dont't see how that reply gets past _select_reply. Maybe it is time to replace that function with filter.

**Comment by TradeFace** [comment]
I did some adjustments in the dev branch. Could you check if this resolves the issue?

**Comment by TradeFace** [comment]
Thanks for the PR, it seems to have a small conflict though. I'll add it manually.

**Comment by TradeFace** [comment]
done!

**Comment by jkerdreux-imt** [comment]
I merged your dev-branch.. but I still have the same issue. 
The issue is not parsing an empty string, but parsing the error from fuzzy protocol version that return:
'json obj data unvalid'

**Comment by TradeFace** [comment]
I rewrote _select_reply 
```
def _select_reply(replies: list):
  
    filtered_replies = list(filter(lambda x: x != 'json obj data unvalid', replies))
    if len(filtered_replies) == 0:
        return None
    return filtered_replies[0]
```
that error"code" shouldn't get through. 

P.S. I don't see the updated function in your fork.

**Comment by jkerdreux-imt** [comment]
I fixed the issue. The lambda should test binary array. missing b'' :)

**Comment by TradeFace** [comment]
Good catch! Thanks
