### ISSUE TITLE
Reduce the number of retry for status()

### ISSUE THREAD

**Issue by jkerdreux-imt** [TradeFace/tuya#27]
By default _status() call add a recurse_cnt to be able to recall it-self on timeout or empty reply. 
This is mainly used to switch from DP_QUERY to CONTROL_NEW if the device reply ''json obj data unvalid' at the DP_QUERY. 

The main issue is that the recurse_cnt max value is 5, and you can't change this. In my experience w/ several devices this cause some trouble more than necessary:

1) If the device is fine = > max =1 is enough because this allows us to test DP_QUERY and next CONTROL_NEW 
2) If the device is disconnected / not present .. you will receive ConnectionResetError (the device drop the cnx) or OSError (device not present). 

But somes devices often refuse to answer if you send them the wrong payload, or if you are to verbose with them. And this occurs mainly in this recursive call. Let's take and example. I send 2 status() or set_status() / status()too quickly. most devices won't answer to the status() request.. and you will end in a loop of 5 recursive call with a timeout of 5 seconds.. 

I think we can drop the timeout to 2 seconds and reduce the max recurse_cnt to something like 3. That will give us max 6 sec which is still very long. 

I apologize for my long list of issues, this one is the last :)

**Comment by TradeFace** [comment]
The recursion count was set arbitrarily. Mostly as a limit. I didn't have any issues with it so far. Be my guest and change to your best insight. Happy to see you PR

**Comment by TradeFace** [comment]
- as per #27
- clean up _connect
- always return json (now json or None)

**Comment by jkerdreux-imt** [comment]
why change the return ? 
I like my code : 
```

        data = retry(tuya.set_state,self.tuya_info,state,idx)
        if data:
            self.on_status(data)
```

**Comment by TradeFace** [comment]
It's more consistent. You'll always get the same return type (dict). You can test for empty dict.

**Comment by TradeFace** [comment]
```
d = {'hello':'world'}
if d:
  print ('not empty')
else:
  print ('empty')

d = {}
if d:
  print ('not empty')
else:
  print ('empty')
```
iow your code should still run the same

**Comment by jkerdreux-imt** [comment]
Ok fine.
