### ISSUE TITLE
Pre-commit triggers (black, mypy, flake, etc)

### ISSUE THREAD

**Issue by emontnemery** [TradeFace/tuya#54]
Would you accept a PR enabling some pre-commit triggers to lint and format the code?

My suggestion is to enable:
- black for consistent code formatting
- mypy since typing information is mostly there already
- flake
- pylint (with not too picky settings)

**Comment by TradeFace** [comment]
Yes sure. I am quite new to python, so I'm interested in to learn about tools and standards
